### ISSUE TITLE
Include PathFinder math

### ISSUE THREAD

**Issue by kvark** [bitshifter/mathbench-rs#3]
https://github.com/servo/pathfinder/blob/71623eaab312ee0c33ba8ffa70954e166b564dfb/geometry/Cargo.toml

This one uses SIMD, but it could be more difficult to hook up. There is no mint support that I can see.

**Comment by bitshifter** [comment]
I had a quick look at adding this, currently on this branch https://github.com/bitshifter/mathbench-rs/tree/pathfinder.

I started with the Euler test and ran into issues because the pathfinder vector types don't support `std::ops::AddAssign` which seemed like fairly basic functionality and I didn't want to rewrite the benchmark to work around this.

Perhaps I should just open an issue asking for them to add it.

**Comment by bitshifter** [comment]
I've added benchmarks for pathfinder_geometry where it made sense. It's pretty minimal compared to the other libraries so I've left it as an optional library but I'll include it's results in the README next time I update it.
